### ISSUE TITLE
Add docker compose for mongodb

### ISSUE THREAD

**Issue by fajarbc** [fajarbc/wa-bot#2]
- [ ] Add docker compose to run mongodb.
Example : `docker-compose.yml`
```yml
version: '3'

services:
  mongo:
    image: mongo
    container_name: mongodb
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - example-net
networks:
  example-net:
    external: true
```

- [ ] Add instruction to run docker compose and manage (to add database seeds) README.md
